version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - .:/odoo
      - ./config/odoo.conf:/odoo/odoo.conf
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    restart: unless-stopped

volumes:
  db_data:
